Add c++ dummy and move files
precice/micro-manager pull request #22
Opened 2023-02-09 11:25 UTC by erikscheurer

This PR adds a C++ solverdummy using pybind11 as discussed in #17. 
The binding with pybind11 seems far easier to us and to users. 
A user could for example use this dummy as a wrapper for their own code or create their own interface with pybind11 by just adding a few lines at the end of their c++ class as in the cpp_dummy here. Compilation is also as easy as with the other approach from #20 

Passing dictionaries between python and c++ is as easy as using `pybind11::dict`. However, for type conversion of the passed data, the user may have to tweak the dummy. How difficult these changes would be, I can't say at the moment without an example. Casting is in any case easier than with the `ctypes` approach from #20.

2023-02-16 15:58 UTC, IshaanDesai commented
Can I already merge this? Also, please merge develop into your branch and overwrite the file `examples/macro-micro-dummy/README.md` that I have created because what you have written up is much better.

2023-02-19 17:50 UTC, erikscheurer commented
No not yet, we observed some weird behavior when increasing the dummy data in each step, that we should maybe test more.

2023-03-06 08:00 UTC, IshaanDesai commented on examples/README.md
> +The `solverdummies` are minimal working examples for using the preCICE micro-manager with different languages. At the moment, there are examples for Python, and C++. They can be coupled with any othe
```suggestion
The `solverdummies` are minimal working examples for using the preCICE Micro Manager with different languages. At the moment, there are examples for Python, and C++. They can be coupled with any other solver, for example the `macro-dummy.py` in this directory.
```

2023-03-06 08:16 UTC, IshaanDesai commented on examples/README.md
> +To run the Python solverdummies, run the following commands in **two different terminals** the `examples` directory:
```suggestion
To run the Python solverdummies, run the following commands in the `examples/` directory in **two different terminals**:
```

2023-03-06 08:22 UTC, IshaanDesai commented on examples/README.md
> +Then, run the following commands in **two different terminals** the `examples` directory:
```suggestion
Then, run the following commands in the `examples/` directory, in **two different terminals**:
```

2023-03-06 10:56 UTC, IshaanDesai commented on examples/cpp-dummy/micro_cpp_dummy.cpp
> +};
Does it make more C++ sense to move this to a `micro_cpp_dummy.hpp` file? If yes, lets do it here too, to be consistent with what a developer in C++ would do.

2023-03-06 11:15 UTC, IshaanDesai commented on examples/cpp-dummy/micro_cpp_dummy.cpp
> +    // create python dict for micro_write_data
```suggestion
    // Convert data to a py::dict again to send it back to the Micro Manager
```

2023-03-06 11:16 UTC, IshaanDesai commented on examples/cpp-dummy/micro_cpp_dummy.cpp
> +}
```suggestion
```

2023-03-06 11:17 UTC, IshaanDesai commented on examples/cpp-dummy/micro_cpp_dummy.cpp
> +    int get_dims();
```suggestion
```

2023-03-06 11:17 UTC, IshaanDesai commented on examples/cpp-dummy/micro_cpp_dummy.cpp
> +    int _dims;
```suggestion
```

2023-03-06 11:19 UTC, IshaanDesai requested changes
Good job! :clap: just some minor points to be done, mostly cleanup. I guess it possible to also have only one `micro-manager-config.json` file, which can then be in the `examples/` directory. Can you check if this works, and if it does, move the file?

2023-03-06 16:37 UTC, merged